#!/usr/bin/env bashio
# shellcheck shell=bash
# Generate /etc/crontabs/root from HA add-on option backup_cron.

set -euo pipefail

OPTIONS_FILE=/data/options.json

# Read a config value via bashio first (real HA), then fall back to reading
# /data/options.json directly with jq. The fallback covers smoke tests and
# any environment where the supervisor API isn't reachable.
get_option() {
  local key="$1"
  local value
  value=$(bashio::config "$key" 2>/dev/null || true)
  if [[ -z "$value" || "$value" == "null" ]] && [[ -f "$OPTIONS_FILE" ]]; then
    value=$(jq -r --arg k "$key" '.[$k] // empty' "$OPTIONS_FILE")
  fi
  echo "$value"
}

BACKUP_CRON=$(get_option 'backup_cron')
: "${BACKUP_CRON:?backup_cron option is empty — check add-on config schema}"

mkdir -p /etc/crontabs
# dcron expects: MIN HOUR DOM MON DOW CMD on a single line.
# It does NOT support PATH= lines in user crontabs (only /etc/cron.d/* system
# crontabs accept env assignments). The backup script sets its own PATH so
# jq/su-exec/pg_dump/gzip/find are found despite cron's minimal environment.
cat > /etc/crontabs/root <<EOF
# Auto-generated by 30-cron-setup.sh — DO NOT EDIT
$BACKUP_CRON /usr/local/bin/forgejo-backup.sh >> /data/backups/.backup.log 2>&1
EOF
chmod 0600 /etc/crontabs/root

# Ensure backup dir exists with sane perms before cron fires (root owns it,
# but the backup script also mkdir -p's it so this is belt-and-suspenders).
mkdir -p /data/backups

bashio::log.info "Backup cron schedule installed: $BACKUP_CRON"
