name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: forgejo/Dockerfile

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: ./forgejo/rootfs
          additional_files: tests/smoke.sh
          ignore_paths: forgejo/rootfs/etc/s6-overlay

      - name: Yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: forgejo/ repository.yaml
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable
              truthy:
                check-keys: false
